-- NimbusCRM initial schema
-- Conventions: uuid PKs generated by the app, org_id tenancy column on all tenant tables,
-- timestamptz UTC everywhere, money as numeric(14,2).

CREATE TABLE organizations (
  id          uuid PRIMARY KEY,
  name        text NOT NULL,
  settings    jsonb NOT NULL DEFAULT '{}',
  created_at  timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE users (
  id            uuid PRIMARY KEY,
  org_id        uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  email         text NOT NULL UNIQUE,
  password_hash text NOT NULL,
  name          text NOT NULL,
  role          text NOT NULL DEFAULT 'member' CHECK (role IN ('admin','manager','member')),
  is_active     boolean NOT NULL DEFAULT true,
  created_at    timestamptz NOT NULL DEFAULT now(),
  updated_at    timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX users_org ON users (org_id);

CREATE TABLE refresh_tokens (
  id         uuid PRIMARY KEY,
  user_id    uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  token_hash text NOT NULL,
  expires_at timestamptz NOT NULL,
  revoked_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX refresh_tokens_user ON refresh_tokens (user_id);
CREATE INDEX refresh_tokens_hash ON refresh_tokens (token_hash);

CREATE TABLE companies (
  id         uuid PRIMARY KEY,
  org_id     uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  name       text NOT NULL,
  domain     text,
  industry   text,
  size       text,
  website    text,
  phone      text,
  address    jsonb NOT NULL DEFAULT '{}',
  owner_id   uuid REFERENCES users(id) ON DELETE SET NULL,
  custom     jsonb NOT NULL DEFAULT '{}',
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX companies_org_name ON companies (org_id, name);

CREATE TABLE contacts (
  id         uuid PRIMARY KEY,
  org_id     uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  first_name text NOT NULL,
  last_name  text NOT NULL DEFAULT '',
  email      text,
  phone      text,
  title      text,
  company_id uuid REFERENCES companies(id) ON DELETE SET NULL,
  owner_id   uuid REFERENCES users(id) ON DELETE SET NULL,
  custom     jsonb NOT NULL DEFAULT '{}',
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX contacts_org_name  ON contacts (org_id, last_name, first_name);
CREATE INDEX contacts_org_email ON contacts (org_id, email);
CREATE INDEX contacts_org_company ON contacts (org_id, company_id);

CREATE TABLE leads (
  id                   uuid PRIMARY KEY,
  org_id               uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  name                 text NOT NULL,
  email                text,
  phone                text,
  company_name         text,
  source               text,
  status               text NOT NULL DEFAULT 'new'
                         CHECK (status IN ('new','contacted','qualified','unqualified','converted')),
  owner_id             uuid REFERENCES users(id) ON DELETE SET NULL,
  custom               jsonb NOT NULL DEFAULT '{}',
  converted_contact_id uuid REFERENCES contacts(id) ON DELETE SET NULL,
  converted_deal_id    uuid,
  created_at           timestamptz NOT NULL DEFAULT now(),
  updated_at           timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX leads_org_status ON leads (org_id, status);
CREATE INDEX leads_org_source ON leads (org_id, source);

CREATE TABLE pipelines (
  id         uuid PRIMARY KEY,
  org_id     uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  name       text NOT NULL,
  is_default boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX pipelines_org ON pipelines (org_id);

CREATE TABLE pipeline_stages (
  id          uuid PRIMARY KEY,
  pipeline_id uuid NOT NULL REFERENCES pipelines(id) ON DELETE CASCADE,
  name        text NOT NULL,
  position    int  NOT NULL,
  probability int  NOT NULL DEFAULT 0 CHECK (probability BETWEEN 0 AND 100),
  is_won      boolean NOT NULL DEFAULT false,
  is_lost     boolean NOT NULL DEFAULT false
);
CREATE INDEX stages_pipeline ON pipeline_stages (pipeline_id, position);

CREATE TABLE deals (
  id                  uuid PRIMARY KEY,
  org_id              uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  title               text NOT NULL,
  value               numeric(14,2) NOT NULL DEFAULT 0,
  currency            text NOT NULL DEFAULT 'USD',
  pipeline_id         uuid NOT NULL REFERENCES pipelines(id) ON DELETE RESTRICT,
  stage_id            uuid NOT NULL REFERENCES pipeline_stages(id) ON DELETE RESTRICT,
  contact_id          uuid REFERENCES contacts(id) ON DELETE SET NULL,
  company_id          uuid REFERENCES companies(id) ON DELETE SET NULL,
  owner_id            uuid REFERENCES users(id) ON DELETE SET NULL,
  status              text NOT NULL DEFAULT 'open' CHECK (status IN ('open','won','lost')),
  lost_reason         text,
  expected_close_date date,
  closed_at           timestamptz,
  custom              jsonb NOT NULL DEFAULT '{}',
  created_at          timestamptz NOT NULL DEFAULT now(),
  updated_at          timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX deals_org_stage  ON deals (org_id, stage_id) WHERE status = 'open';
CREATE INDEX deals_org_closed ON deals (org_id, closed_at) WHERE status = 'won';
CREATE INDEX deals_org_owner  ON deals (org_id, owner_id);
CREATE INDEX deals_org_pipeline ON deals (org_id, pipeline_id);

ALTER TABLE leads
  ADD CONSTRAINT leads_converted_deal_fk
  FOREIGN KEY (converted_deal_id) REFERENCES deals(id) ON DELETE SET NULL;

CREATE TABLE tasks (
  id           uuid PRIMARY KEY,
  org_id       uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  title        text NOT NULL,
  description  text NOT NULL DEFAULT '',
  due_date     timestamptz,
  priority     text NOT NULL DEFAULT 'medium' CHECK (priority IN ('low','medium','high')),
  status       text NOT NULL DEFAULT 'open' CHECK (status IN ('open','done')),
  assignee_id  uuid REFERENCES users(id) ON DELETE SET NULL,
  related_type text,
  related_id   uuid,
  created_by   uuid REFERENCES users(id) ON DELETE SET NULL,
  completed_at timestamptz,
  created_at   timestamptz NOT NULL DEFAULT now(),
  updated_at   timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX tasks_org_assignee ON tasks (org_id, assignee_id, status, due_date);
CREATE INDEX tasks_org_related  ON tasks (org_id, related_type, related_id);

CREATE TABLE notes (
  id           uuid PRIMARY KEY,
  org_id       uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  body         text NOT NULL,
  related_type text NOT NULL,
  related_id   uuid NOT NULL,
  author_id    uuid REFERENCES users(id) ON DELETE SET NULL,
  created_at   timestamptz NOT NULL DEFAULT now(),
  updated_at   timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX notes_org_related ON notes (org_id, related_type, related_id, created_at DESC);

CREATE TABLE activities (
  id          uuid PRIMARY KEY,
  org_id      uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  type        text NOT NULL,
  actor_id    uuid REFERENCES users(id) ON DELETE SET NULL,
  entity_type text NOT NULL,
  entity_id   uuid NOT NULL,
  payload     jsonb NOT NULL DEFAULT '{}',
  created_at  timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX activities_org_entity ON activities (org_id, entity_type, entity_id, created_at DESC);
CREATE INDEX activities_org_created ON activities (org_id, created_at DESC);

CREATE TABLE audit_logs (
  id          uuid PRIMARY KEY,
  org_id      uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  actor_id    uuid,
  action      text NOT NULL,
  entity_type text NOT NULL,
  entity_id   uuid,
  changes     jsonb NOT NULL DEFAULT '{}',
  created_at  timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX audit_org_created ON audit_logs (org_id, created_at DESC);
CREATE INDEX audit_org_entity  ON audit_logs (org_id, entity_type, entity_id);

CREATE TABLE custom_field_defs (
  id          uuid PRIMARY KEY,
  org_id      uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  entity_type text NOT NULL CHECK (entity_type IN ('contact','company','lead','deal')),
  key         text NOT NULL,
  label       text NOT NULL,
  field_type  text NOT NULL CHECK (field_type IN ('text','number','date','select','checkbox')),
  options     jsonb NOT NULL DEFAULT '[]',
  required    boolean NOT NULL DEFAULT false,
  position    int NOT NULL DEFAULT 0,
  created_at  timestamptz NOT NULL DEFAULT now(),
  UNIQUE (org_id, entity_type, key)
);

CREATE TABLE workflows (
  id           uuid PRIMARY KEY,
  org_id       uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  name         text NOT NULL,
  trigger_type text NOT NULL,
  conditions   jsonb NOT NULL DEFAULT '[]',
  actions      jsonb NOT NULL DEFAULT '[]',
  is_active    boolean NOT NULL DEFAULT true,
  created_at   timestamptz NOT NULL DEFAULT now(),
  updated_at   timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX workflows_org_trigger ON workflows (org_id, trigger_type) WHERE is_active;

CREATE TABLE workflow_runs (
  id          uuid PRIMARY KEY,
  workflow_id uuid NOT NULL REFERENCES workflows(id) ON DELETE CASCADE,
  org_id      uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  event       jsonb NOT NULL DEFAULT '{}',
  status      text NOT NULL CHECK (status IN ('success','partial','failed')),
  detail      jsonb NOT NULL DEFAULT '{}',
  created_at  timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX workflow_runs_wf ON workflow_runs (workflow_id, created_at DESC);

CREATE TABLE notifications (
  id          uuid PRIMARY KEY,
  org_id      uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  user_id     uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  type        text NOT NULL,
  title       text NOT NULL,
  body        text NOT NULL DEFAULT '',
  entity_type text,
  entity_id   uuid,
  read_at     timestamptz,
  created_at  timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX notif_user_created ON notifications (user_id, created_at DESC);
CREATE INDEX notif_user_unread  ON notifications (user_id, created_at DESC) WHERE read_at IS NULL;

CREATE TABLE files (
  id           uuid PRIMARY KEY,
  org_id       uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  filename     text NOT NULL,
  mime         text NOT NULL,
  size         bigint NOT NULL,
  storage_key  text NOT NULL,
  related_type text,
  related_id   uuid,
  uploaded_by  uuid REFERENCES users(id) ON DELETE SET NULL,
  created_at   timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX files_org_related ON files (org_id, related_type, related_id);
